version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-test
    command: npm start # comando a executar
    restart: unless-stopped # reiniciar sempre que da error
    env_file: ./.env
    ports:
      - 80:3333
      # - $NODE_LOCAL_PORTS:$NODE_DOCKER_PORTS # chama a porta do local 3000 para a do container 3000
    volumes:
      - .:/usr/app # monitoro a pasta atual . e envio as alterações para /usr/app

